/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AnimatedButton {
    }
}
declare global {
    interface HTMLAnimatedButtonElement extends Components.AnimatedButton, HTMLStencilElement {
    }
    var HTMLAnimatedButtonElement: {
        prototype: HTMLAnimatedButtonElement;
        new (): HTMLAnimatedButtonElement;
    };
    interface HTMLElementTagNameMap {
        "animated-button": HTMLAnimatedButtonElement;
    }
}
declare namespace LocalJSX {
    interface AnimatedButton {
    }
    interface IntrinsicElements {
        "animated-button": AnimatedButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "animated-button": LocalJSX.AnimatedButton & JSXBase.HTMLAttributes<HTMLAnimatedButtonElement>;
        }
    }
}
